NuanLib: examples/lagrange_example.cpp File Reference
lagrange_example.cpp File Reference
#include <iostream>
#include <cmath>
#include <iomanip>
#include "../lib/interpolation/lagrange.hpp"
Functions
double function (double x)
double * division_into_segments (double a, double b, size_t segmentsNum)
double * y_values (const double *x, size_t size)
double delta_value (double interpolated, double func)
int main ()
Function Documentation
delta_value()
double delta_value (double interpolated, double func)
Examples
lagrange_example.cpp.
Definition at line 94 of file lagrange_example.cpp.
Referenced by main().
division_into_segments()
double * division_into_segments (double a, double b, size_t segmentsNum)
Examples
lagrange_example.cpp.
Definition at line 59 of file lagrange_example.cpp.
Referenced by main().
function()
double function (double x)
Examples
lagrange_example.cpp.
Definition at line 73 of file lagrange_example.cpp.
Referenced by y_values().
main()
int main ()
Examples
lagrange_example.cpp.
Definition at line 15 of file lagrange_example.cpp.
References delta_value(), division_into_segments(), nuan::interpolation::lagrange_polynomial(), and y_values().
y_values()
double * y_values (const double * x, size_t size)
Examples
lagrange_example.cpp.
Definition at line 81 of file lagrange_example.cpp.
References function().
Referenced by main().