NuanLib: nuan::integration Namespace Reference
nuan::integration Namespace Reference
Functions
template<typename T >
std::vector< T > euler_method (T(*diff_f)(T, T), T initial_value, T a, T b, T step=0.01)
template<typename T >
T left_rectangle (T(*func)(T), T a, T b, T step=0.01)
template<typename T >
T right_rectangle (T(*func)(T), T a, T b, T step=0.01)
template<typename T >
std::vector< T > runge_kutta (T(*diff_f)(T, T), T initial_value, T a, T b, T step=0.01)
template<typename T >
T simpsons_rule (T(*func)(T), T a, T b, T step=0.01)
template<typename T >
T trapezoidal_rule (T(*func)(T), T a, T b, T step=0.01)
Function Documentation
euler_method()
template<typename T > std::vector< T > nuan::integration::euler_method (T(*)(T, T) diff_f, T initial_value, T a, T b, T step = 0.01)
Numerical solution of the Cauchy problem by the Euler method.
Template Parameters
T Any float-point type such as float, double or long double
Parameters
diff_f Function describing the Cauchy problem u' = f(u, x)
initial_value Initial condition at start point
a start point
b end point
step the step of changing the variable x.
Returns
solutions of the Cauchy problem represents as a vector.
Warning
Throws Integration_Range_Error exception when the a >= b.
See also
https://en.wikipedia.org/wiki/Cauchy_problem
https://en.wikipedia.org/wiki/Euler_method
Examples
euler_example.cpp.
Definition at line 23 of file euler.hpp.
Referenced by main().
left_rectangle()
template<typename T > T nuan::integration::left_rectangle (T(*)(T) func, T a, T b, T step = 0.01)
Numerical solution of the integrals using left rectangles.
Template Parameters
T Any float-point type such as float, double or long double
Parameters
func integrand
a start point
b end point
step the step of changing the variable x.
Returns
approximate integral value.
Warning
Throws Integration_Range_Error exception when the a >= b.
See also
https://www.expii.com/t/left-right-and-midpoint-riemann-sums-244
Examples
left_rectangle_example.cpp.
Definition at line 21 of file left_rectangle.hpp.
Referenced by main().
right_rectangle()
template<typename T > T nuan::integration::right_rectangle (T(*)(T) func, T a, T b, T step = 0.01)
Numerical solution of the integrals using right rectangles.
Template Parameters
T Any float-point type such as float, double or long double
Parameters
func integrand
a start point
b end point
step the step of changing the variable x.
Returns
approximate integral value.
Warning
Throws Integration_Range_Error exception when the a >= b.
See also
https://www.expii.com/t/left-right-and-midpoint-riemann-sums-244
Examples
right_rectangle_example.cpp.
Definition at line 21 of file right_rectangle.hpp.
Referenced by main().
runge_kutta()
template<typename T > std::vector< T > nuan::integration::runge_kutta (T(*)(T, T) diff_f, T initial_value, T a, T b, T step = 0.01)
Numerical solution of the Cauchy problem by the Runge–Kutta method.
Template Parameters
T Any float-point type such as float, double or long double
Parameters
diff_f Function describing the Cauchy problem u' = f(u, x)
initial_value Initial condition at start point
a start point
b end point
step the step of changing the variable x.
Returns
solutions of the Cauchy problem represents as a vector.
Warning
Throws Integration_Range_Error exception when the a >= b.
See also
https://en.wikipedia.org/wiki/Cauchy_problem
https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta_methods
Examples
runge_kutta_example.cpp.
Definition at line 24 of file runge_kutta.hpp.
Referenced by main().
simpsons_rule()
template<typename T > T nuan::integration::simpsons_rule (T(*)(T) func, T a, T b, T step = 0.01)
Numerical solution of the integrals using simpsons rule.
Template Parameters
T Any float-point type such as float, double or long double
Parameters
func integrand
a start point
b end point
step the step of changing the variable x.
Returns
approximate integral value.
Warning
Throws Integration_Range_Error exception when the a >= b.
See also
https://en.wikipedia.org/wiki/Simpson's_rule
Examples
simpsons_rule_example.cpp.
Definition at line 21 of file simpsons_rule.hpp.
Referenced by main().
trapezoidal_rule()
template<typename T > T nuan::integration::trapezoidal_rule (T(*)(T) func, T a, T b, T step = 0.01)
Numerical solution of the integrals using trapezoidal rule.
Template Parameters
T Any float-point type such as float, double or long double
Parameters
func integrand
a start point
b end point
step the step of changing the variable x.
Returns
approximate integral value.
Warning
Throws Integration_Range_Error exception when the a >= b.
See also
https://en.wikipedia.org/wiki/Trapezoidal_rule
Examples
trapezoidal_rule_example.cpp.
Definition at line 21 of file trapezoidal_rule.hpp.
Referenced by main().